### ISSUE TITLE
Create Content Module

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.com#126]
As discussed. This module will use content from tnd.dev

Use the "video" section. This is the closest thing we have to past events. Maybe want want only ones with a certain tag or front matter value?

I suppose the module will be flexible enough to accommodate us changing the content section.

**Comment by regisphilibert** [comment]
Oh I thought we only wanted to import the videos from tnd.org
My vision was to have the tnd.com project import the tnd.org repo as a module and configure mounts to accommodate:

```yaml
module:
  - path: github.com/theNewDynamic/thenewdynamic.org
    mounts:
      source: content/video
      target: content/events
      lang: en
```

Then it will be the responsibility of tnd.com project to filter what video we want to use.

But maybe you want to move all of tnd.com content to a module?
