### ISSUE TITLE
Create blocks for open source

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.com#52]
- [ ] Add fields to Netlify CMS
- [ ] the entire card should be a link to the repo. Hover state should change the shadow (shadow:none)

```
blocks:
  - type: cards
    layout: cards
    title: Our Open Source Contributions
    points:
      - title: SEO Module
        intro: >-
          A module loaded up for awesome SEO
        type: Hugo Module
        status: Alpha
        repo: /tnd-hugo-module-seo/
```
The above front matter layout is for example only (re: blocks/cards). The fields match those in the Figma mockup 

https://www.figma.com/file/I8F9jSigCKVROyBXeKX04W/Untitled?node-id=0%3A1
